import type { FieldDef } from '@/lib/types';

// Shared Kanban task template used when a folder has no persisted template.
export const DEFAULT_KANBAN_FIELDS: FieldDef[] = [
  {
    key: 'title',
    label: '任务名称',
    type: 'text',
    show_on_card: true,
    show_in_detail: true,
    required: true,
    order: 1,
    system: true,
    editable: true,
    default_value: '',
  },
  {
    key: 'version',
    label: '所属版本',
    type: 'text',
    show_on_card: true,
    show_in_detail: true,
    required: false,
    order: 2,
    system: true,
    editable: true,
    default_value: '',
  },
  {
    key: 'task_type',
    label: '任务类型',
    type: 'select',
    show_on_card: true,
    show_in_detail: true,
    required: true,
    order: 3,
    system: true,
    editable: true,
    default_value: 'feature',
    options: ['feature', 'bug', 'chore', 'refactor', 'docs', 'test'],
  },
  {
    key: 'priority',
    label: '优先级',
    type: 'select',
    show_on_card: true,
    show_in_detail: true,
    required: true,
    order: 4,
    system: true,
    editable: true,
    default_value: 'P2',
    options: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    key: 'requirement_desc',
    label: '需求说明',
    type: 'textarea',
    show_on_card: false,
    show_in_detail: true,
    required: false,
    order: 5,
    system: true,
    editable: true,
    default_value: '',
  },
  {
    key: 'technical_desc',
    label: '技术说明',
    type: 'textarea',
    show_on_card: false,
    show_in_detail: true,
    required: false,
    order: 6,
    system: true,
    editable: true,
    default_value: '',
  },
  {
    key: 'acceptance_criteria',
    label: '验收标准',
    type: 'textarea',
    show_on_card: false,
    show_in_detail: true,
    required: false,
    order: 7,
    system: true,
    editable: true,
    default_value: '',
  },
];

export function resolveKanbanFields(fields?: FieldDef[] | null): FieldDef[] {
  const source = fields && fields.length > 0 ? fields : DEFAULT_KANBAN_FIELDS;
  return source.map((field) => ({ ...field }));
}
