#!/usr/bin/env python3
"""
Lightweight PlantUML linter for diagrams generated by universal-uml-diagrammer.

Usage:
  python scripts/lint-puml.py docs/uml

Checks:
- .puml files contain @startuml and @enduml
- each diagram has a title
- each diagram has scope and evidence comments
- rough node limits by diagram type
- discouraged placeholder names
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PLACEHOLDER_PATTERNS = [
    r"\bUnknown\b",
    r"\bTBD\b",
    r"\bTODO\b",
    r"\bSomeService\b",
    r"\bSomeClass\b",
    r"\bExampleService\b",
    r"\bExampleClass\b",
    r"\bManager\b",
    r"\bHelper\b",
]

NODE_PATTERNS = [
    r"^\s*(abstract\s+class|class|interface|enum|entity|component|database|queue|cloud|node|actor|participant|boundary|control|collections|object|package|rectangle|usecase|state)\b"
]

LIMITS = {
    "class": 25,
    "object": 20,
    "package": 30,
    "component": 25,
    "deployment": 25,
    "composite": 25,
    "profile": 25,
    "usecase": 25,
    "use-case": 25,
    "activity": 40,
    "state": 30,
    "sequence": 12,
    "communication": 25,
    "interaction": 25,
    "timing": 8,
    "erd": 30,
    "database": 30,
    "c4": 25,
    "dfd": 25,
    "flowchart": 40,
    "api": 25,
    "event": 30,
    "domain": 30,
    "context-map": 25,
}


def infer_diagram_type(path: Path, text: str) -> str:
    parts = [p.lower() for p in path.parts]
    for key in LIMITS:
        if key in parts:
            return key

    lower = text.lower()
    if "robust " in lower and "@" in text:
        return "timing"
    if "usecase " in lower:
        return "usecase"
    if "start" in lower and "stop" in lower:
        return "activity"
    if re.search(r"^\s*state\s+", text, re.MULTILINE) or "[*]" in text:
        return "state"
    if "participant " in lower or "actor " in lower and "->" in text:
        return "sequence"
    if "entity " in lower:
        return "erd"
    if "database " in lower or "queue " in lower or "component " in lower:
        return "component"
    if "class " in lower or "interface " in lower:
        return "class"
    return "unknown"


def count_nodes(text: str) -> int:
    count = 0
    for line in text.splitlines():
        if any(re.search(pattern, line, re.IGNORECASE) for pattern in NODE_PATTERNS):
            count += 1
    return count


def count_timing_lifelines(text: str) -> int:
    return len(re.findall(r"^\s*(robust|concise|binary|clock)\s+", text, re.MULTILINE | re.IGNORECASE))


def lint_file(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    errors: list[str] = []

    if "@startuml" not in text:
        errors.append("missing @startuml")
    if "@enduml" not in text:
        errors.append("missing @enduml")
    if not re.search(r"^\s*title\s+.+", text, re.MULTILINE | re.IGNORECASE):
        errors.append("missing title")
    if not re.search(r"^\s*'\s*Scope\s*:", text, re.MULTILINE | re.IGNORECASE):
        errors.append("missing scope comment")
    if not re.search(r"^\s*'\s*Evidence\s*:", text, re.MULTILINE | re.IGNORECASE):
        errors.append("missing evidence comment")

    for pattern in PLACEHOLDER_PATTERNS:
        if re.search(pattern, text):
            errors.append(f"discouraged placeholder or vague name: {pattern}")

    diagram_type = infer_diagram_type(path, text)
    limit = LIMITS.get(diagram_type)

    if diagram_type == "timing":
        nodes = count_timing_lifelines(text)
    else:
        nodes = count_nodes(text)

    if limit is not None and nodes > limit:
        errors.append(f"too many nodes for {diagram_type} diagram: {nodes} > {limit}")

    return errors


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: lint-puml.py <path>", file=sys.stderr)
        return 2

    root = Path(sys.argv[1])
    files = list(root.rglob("*.puml")) if root.is_dir() else [root]

    if not files:
        print(f"No .puml files found under {root}")
        return 0

    failed = False
    for file in sorted(files):
        errors = lint_file(file)
        if errors:
            failed = True
            print(f"\n{file}")
            for error in errors:
                print(f"  - {error}")

    if failed:
        print("\nPlantUML lint failed.")
        return 1

    print(f"PlantUML lint passed for {len(files)} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
