import dayjs from 'dayjs';
import type { CalendarEvent, CalendarSource, CalendarSubscription } from './calendarTypes';

export const SOURCE_COLORS = {
  manual: '#6C5CE7',
  todo: '#3B82F6',
  finance_income: '#10B981',
  finance_expense: '#EF4444',
  bill: '#F59E0B',
  holiday: '#EF4444',
  subscription: '#8B5CF6',
} as const;

export const MOCK_SOURCES: CalendarSource[] = [
  { id: 'src-manual', name: '我的日历', type: 'manual', color: SOURCE_COLORS.manual, visible: true, readonly: false, icon: 'calendar' },
  { id: 'src-todo', name: '任务', type: 'todo', color: SOURCE_COLORS.todo, visible: true, readonly: true, icon: 'task' },
  { id: 'src-income', name: '收入', type: 'finance_income', color: SOURCE_COLORS.finance_income, visible: true, readonly: true, icon: 'income' },
  { id: 'src-expense', name: '支出', type: 'finance_expense', color: SOURCE_COLORS.finance_expense, visible: true, readonly: true, icon: 'expense' },
  { id: 'src-bill', name: '账单提醒', type: 'bill', color: SOURCE_COLORS.bill, visible: true, readonly: false, icon: 'bill' },
  { id: 'src-holiday', name: '中国节假日', type: 'holiday', color: SOURCE_COLORS.holiday, visible: true, readonly: true, icon: 'holiday' },
  { id: 'src-sub', name: '订阅日历', type: 'subscription', color: SOURCE_COLORS.subscription, visible: true, readonly: true, icon: 'subscription', syncUrl: 'https://example.com/calendar.ics' },
];

export const MOCK_SUBSCRIPTIONS: CalendarSubscription[] = [
  {
    id: 'sub-team',
    name: '团队共享日历',
    url: 'https://example.com/team.ics',
    color: SOURCE_COLORS.subscription,
    enabled: true,
    lastSyncedAt: dayjs().subtract(2, 'hour').toISOString(),
  },
];

const currentMonth = dayjs();

const sampleEvents: CalendarEvent[] = [
  {
    id: 'evt-standup',
    title: '团队周会',
    description: '同步本周任务进度和风险',
    startAt: currentMonth.date(5).hour(10).minute(0).second(0).toISOString(),
    endAt: currentMonth.date(5).hour(11).minute(0).second(0).toISOString(),
    allDay: false,
    sourceId: 'src-manual',
    sourceType: 'manual',
    color: SOURCE_COLORS.manual,
    icon: 'calendar',
    location: '线上会议',
    repeatRule: 'weekly',
    reminder: '15m',
    readonly: false,
    createdAt: dayjs().toISOString(),
    updatedAt: dayjs().toISOString(),
  },
  {
    id: 'todo-api-docs',
    title: '完成 API 文档',
    startAt: currentMonth.date(8).format('YYYY-MM-DD'),
    allDay: true,
    sourceId: 'src-todo',
    sourceType: 'todo',
    color: SOURCE_COLORS.todo,
    icon: 'task',
    repeatRule: 'none',
    reminder: '1d',
    readonly: true,
    linkedModule: 'todo',
    linkedObjectId: 'todo-101',
    status: 'pending',
    createdAt: dayjs().toISOString(),
    updatedAt: dayjs().toISOString(),
  },
  {
    id: 'fin-salary',
    title: '工资到账',
    startAt: currentMonth.date(10).format('YYYY-MM-DD'),
    allDay: true,
    sourceId: 'src-income',
    sourceType: 'finance_income',
    color: SOURCE_COLORS.finance_income,
    icon: 'income',
    repeatRule: 'monthly',
    reminder: 'none',
    readonly: true,
    linkedModule: 'finance',
    linkedObjectId: 'fin-001',
    amount: 18000,
    direction: 'income',
    createdAt: dayjs().toISOString(),
    updatedAt: dayjs().toISOString(),
  },
  {
    id: 'bill-rent',
    title: '房租缴费',
    startAt: currentMonth.date(15).format('YYYY-MM-DD'),
    allDay: true,
    sourceId: 'src-bill',
    sourceType: 'bill',
    color: SOURCE_COLORS.bill,
    icon: 'bill',
    repeatRule: 'monthly',
    reminder: '1d',
    readonly: false,
    amount: 4200,
    direction: 'expense',
    createdAt: dayjs().toISOString(),
    updatedAt: dayjs().toISOString(),
  },
  {
    id: 'fin-shopping',
    title: '日用品采购',
    startAt: currentMonth.date(18).format('YYYY-MM-DD'),
    allDay: true,
    sourceId: 'src-expense',
    sourceType: 'finance_expense',
    color: SOURCE_COLORS.finance_expense,
    icon: 'expense',
    repeatRule: 'none',
    reminder: 'none',
    readonly: true,
    linkedModule: 'finance',
    linkedObjectId: 'fin-002',
    amount: 386,
    direction: 'expense',
    createdAt: dayjs().toISOString(),
    updatedAt: dayjs().toISOString(),
  },
  {
    id: 'sub-release',
    title: '产品发布复盘',
    startAt: currentMonth.date(22).hour(15).minute(30).second(0).toISOString(),
    endAt: currentMonth.date(22).hour(16).minute(30).second(0).toISOString(),
    allDay: false,
    sourceId: 'src-sub',
    sourceType: 'subscription',
    color: SOURCE_COLORS.subscription,
    icon: 'subscription',
    repeatRule: 'none',
    reminder: '1h',
    readonly: true,
    location: '共享日历',
    createdAt: dayjs().toISOString(),
    updatedAt: dayjs().toISOString(),
  },
];

const holidayEvents: CalendarEvent[] = [
  ['2026-06-19', '端午节'],
  ['2026-10-01', '国庆节'],
  ['2026-10-04', '中秋节'],
].map(([date, title]) => ({
  id: `holiday-${date}`,
  title,
  startAt: date,
  allDay: true,
  sourceId: 'src-holiday',
  sourceType: 'holiday',
  color: SOURCE_COLORS.holiday,
  icon: 'holiday',
  repeatRule: 'none',
  reminder: 'none',
  readonly: true,
  createdAt: dayjs().toISOString(),
  updatedAt: dayjs().toISOString(),
}));

export function getAllMockEvents(): CalendarEvent[] {
  return [...sampleEvents, ...holidayEvents];
}

